"""Edited Question DB

Revision ID: 181af276f7d9
Revises: 1e1196f3b44a
Create Date: 2025-01-09 13:17:37.426487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181af276f7d9'
down_revision = '1e1196f3b44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('option1',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('option2',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('option3',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('option4',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('option4',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('option3',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('option2',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('option1',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
