"""Added Columns for Question Images

Revision ID: 1e1196f3b44a
Revises: f09bd39add62
Create Date: 2025-01-09 13:09:09.479113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1196f3b44a'
down_revision = 'f09bd39add62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('option1_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('option2_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('option3_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('option4_image', sa.String(length=200), nullable=True))

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('option4_image')
        batch_op.drop_column('option3_image')
        batch_op.drop_column('option2_image')
        batch_op.drop_column('option1_image')
        batch_op.drop_column('question_image')

    # ### end Alembic commands ###
