"""Added Parially Correct Questions column

Revision ID: dac9520fdcd9
Revises: b182c6d6db68
Create Date: 2025-01-11 12:19:11.689595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac9520fdcd9'
down_revision = 'b182c6d6db68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partially_correct_answers', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('partially_correct_answers')

    # ### end Alembic commands ###
